export { Dashboard } from './Dashboard';
export { ForgotPassword } from './ForgotPassword';
export { Inventario } from './Inventario';
export { Login } from './Login';
export { Movimentacoes } from './Movimentacoes';
export { PerfisAcesso } from './PerfisAcesso';
export { Relatorios } from './Relatorios';
export { ResetPassword } from './ResetPassword';
export { Usuarios } from './Usuarios';
